import {
  SiCss3,
  SiD3Dotjs,
  SiExpress,
  SiGit,
  SiGithub,
  SiGitlab,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiMantine,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPython,
  SiReact,
  SiRedux,
  SiSass,
  SiStorybook,
  SiStyledcomponents,
  SiTypescript,
  SiTailwindcss,
} from 'react-icons/si';
import { TbApi, TbBrandReactNative, TbTestPipe } from 'react-icons/tb';
import type { IconType } from 'react-icons';

// Icon mapping from JSON icon names to React Icons
export const iconMapping: Record<string, IconType> = {
  react: SiReact,
  typescript: SiTypescript,
  javascript: SiJavascript,
  html5: SiHtml5,
  css3: SiCss3,
  sass: SiSass,
  'react-native': TbBrandReactNative,
  nextjs: SiNextdotjs,
  'styled-components': SiStyledcomponents,
  mantine: SiMantine,
  tailwindcss: SiTailwindcss,
  jest: SiJest,
  playwright: TbTestPipe,
  storybook: SiStorybook,
  git: SiGit,
  github: SiGithub,
  gitlab: SiGitlab,
  nodejs: SiNodedotjs,
  python: SiPython,
  mongodb: SiMongodb,
  sql: SiMysql,
  express: SiExpress,
  api: TbApi,
  redux: SiRedux,
  d3js: SiD3Dotjs,
  expo: SiReact, // Using React icon as fallback for Expo
  zustand: SiReact, // Fallback icon for Zustand
};
